FROM ubuntu:14.04
MAINTAINER Grant Heffernan <grant@mapzen.com>

ENV TERM vt100

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install jq supervisor software-properties-common -y

ADD ./scripts /scripts
RUN /scripts/install_from_source.sh

ADD ./conf /conf

RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8002
CMD ["/scripts/start_valhalla.sh"]
