FROM ubuntu:14.04
MAINTAINER Grant Heffernan <grant@mapzen.com>

ENV TERM                vt100
ENV PPA_VERSION         ${PPA_VERSION:-""}

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install jq supervisor -y

ADD ./scripts /scripts
RUN /scripts/install_from_ppa.sh

ADD ./conf /conf

RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8002
CMD ["/scripts/start_valhalla.sh"]
